"""Unit tests for the pure logic in the local platform tooling.

Run via `make check`, or directly:

    python3 -m unittest discover -s ./local-platform -p 'test_*.py'

Everything here is hermetic (no docker, no network); the few tests that use
external binaries (bash for source-equivalence, openssl/node for the JWT)
skip themselves when the binary is missing.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from localplatform.bootstrap import _REDACT_PATTERN, sign_edge_grpc_token
from localplatform.ensure_compiled import _build_package_list
from localplatform.lib import (
    Ctx,
    Fail,
    describe_artifact_source,
    describe_backend_version,
    format_duration,
    human_bytes,
    is_truthy,
    parse_env_file,
    read_resolved_json,
    write_env_file,
)


class TempDirTest(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)

    def write(self, name: str, content: str) -> Path:
        path = self.tmp / name
        path.write_text(content)
        return path


class TestEnvFileScanner(TempDirTest):
    def parse(self, content: str, base: dict[str, str] | None = None):
        return parse_env_file(self.write("t.env", content), base_env=base or {})

    def test_generated_test_env_shape(self) -> None:
        parsed = self.parse(
            "#!/usr/bin/env bash\n"
            "# Generated by smbe local-dev-env.\n"
            'export WASMER_REGISTRY="http://backend:8000/graphql"\n'
            'export WASMER_TOKEN="wap_abc123"\n'
            "\n"
            'export EDGE_SERVER="http://127.0.0.1:19080"\n'
        )
        self.assertEqual(
            parsed,
            {
                "WASMER_REGISTRY": "http://backend:8000/graphql",
                "WASMER_TOKEN": "wap_abc123",
                "EDGE_SERVER": "http://127.0.0.1:19080",
            },
        )

    def test_quote_semantics(self) -> None:
        parsed = self.parse(
            "export BASE=hello\n"
            'export DOUBLE="$BASE world"\n'
            "export UNQUOTED=$BASE-suffix\n"
            "export SINGLE='$BASE stays'\n"
            'export BRACED="${BASE}_x"\n'
            'export FROM_CALLER="$CALLER!"\n'
            'export MISSING="$NOPE-"\n',
            base={"CALLER": "outer"},
        )
        self.assertEqual(parsed["DOUBLE"], "hello world")
        self.assertEqual(parsed["UNQUOTED"], "hello-suffix")
        self.assertEqual(parsed["SINGLE"], "$BASE stays")
        self.assertEqual(parsed["BRACED"], "hello_x")
        self.assertEqual(parsed["FROM_CALLER"], "outer!")
        self.assertEqual(parsed["MISSING"], "-")

    def test_default_expansion(self) -> None:
        parsed = self.parse(
            "export PORT=${EDGE_HTTP_PORT:-19080}\nexport SET=${KNOWN:-fb}\n",
            base={"KNOWN": "known"},
        )
        self.assertEqual(parsed["PORT"], "19080")
        self.assertEqual(parsed["SET"], "known")

    def test_multiline_value(self) -> None:
        source = {"LOCAL_TEST_COMMAND": "npx jest a\nnpx jest b", "X": "y"}
        path = self.tmp / "multi.env"
        write_env_file(path, source)
        self.assertEqual(parse_env_file(path, base_env={}), source)

    def test_legacy_printf_q_format(self) -> None:
        parsed = self.parse(
            "export LOCAL_TEST_COMMAND=$'npx jest a\\nnpx jest b'\n"
            "export SIMPLE=pnpm\\ exec\\ jest\n"
            "export DOLLAR=lit\\ \\$HOME\\ x\n"
        )
        self.assertEqual(parsed["LOCAL_TEST_COMMAND"], "npx jest a\nnpx jest b")
        self.assertEqual(parsed["SIMPLE"], "pnpm exec jest")
        self.assertEqual(parsed["DOLLAR"], "lit $HOME x")

    def test_comments_and_hash_values(self) -> None:
        parsed = self.parse("export A=1 # trailing comment\nexport B='x # kept'\n")
        self.assertEqual(parsed, {"A": "1", "B": "x # kept"})

    def test_command_substitution_fails_loudly(self) -> None:
        with self.assertRaisesRegex(Fail, "command substitution"):
            self.parse("export X=$(cat foo)\n")
        with self.assertRaisesRegex(Fail, "backtick"):
            self.parse("export X=`date`\n")

    def test_unsupported_expansion_fails_loudly(self) -> None:
        with self.assertRaisesRegex(Fail, "unsupported parameter expansion"):
            self.parse("export X=${FOO:?required}\n")

    def test_roundtrip_tricky_values(self) -> None:
        source = {
            "WITH_SPACES": 'pnpm exec jest -t "some test"',
            "WITH_SINGLE": "it's a value",
            "WITH_DOLLAR": "literal $HOME here",
            "EMPTY": "",
            "URL": "http://localhost:18000/graphql?a=b&c=d",
        }
        path = self.tmp / "round.env"
        write_env_file(path, source)
        self.assertEqual(parse_env_file(path, base_env={}), source)

    @unittest.skipUnless(shutil.which("bash"), "bash not available")
    def test_written_files_source_identically_in_bash(self) -> None:
        source = {
            "LOCAL_TEST_COMMAND": "npx jest a\nnpx jest b",
            "WITH_DOLLAR": "literal $HOME here",
            "WITH_SPACES": 'a "b" c',
        }
        path = self.tmp / "bash.env"
        write_env_file(path, source)
        script = (
            f'set -a; source "{path}"; set +a; '
            "python3 -c 'import os,json;print(json.dumps("
            "{k: os.environ[k] for k in (\"LOCAL_TEST_COMMAND\",\"WITH_DOLLAR\",\"WITH_SPACES\")}))'"
        )
        output = subprocess.run(
            ["bash", "-c", script],
            capture_output=True,
            text=True,
            env={"PATH": os.environ["PATH"]},
        )
        self.assertEqual(json.loads(output.stdout), source)


class TestCtxDefaults(unittest.TestCase):
    def test_empty_counts_as_unset(self) -> None:
        ctx = Ctx(env={"LOCAL_PLATFORM_EDGE_CACHE_DIR": "", "BACKEND_HTTP_PORT": ""})
        self.assertTrue(str(ctx.edge_cache_dir()).endswith(".local-platform/cache/edge"))
        ctx.set_default_ports()
        self.assertEqual(ctx.env["BACKEND_HTTP_PORT"], "18000")

    def test_truthy_gates(self) -> None:
        ctx = Ctx(env={"EMPTY": "", "ZERO": "0", "ON": "1"})
        self.assertTrue(ctx.truthy("EMPTY", "1"), "set-but-empty falls back to default")
        self.assertFalse(ctx.truthy("ZERO", "1"))
        self.assertTrue(ctx.truthy("ON"))
        self.assertTrue(ctx.truthy("ABSENT", "1"))
        self.assertFalse(ctx.truthy("ABSENT"))

    def test_is_truthy_spellings(self) -> None:
        for falsy in ("", "0", "false", "FALSE", "no", "No", "off", "OFF"):
            self.assertFalse(is_truthy(falsy), falsy)
        for truthy in ("1", "true", "yes", "on", "anything"):
            self.assertTrue(is_truthy(truthy), truthy)


class TestResolvedJson(TempDirTest):
    def test_roundtrip_matches_env_shape(self) -> None:
        path = self.write(
            "resolved.json",
            json.dumps(
                {
                    "backend_version": "resolve_prod",
                    "edge_version": "resolve_dev",
                    "backend_image_ref": "ghcr.io/x/y:1",
                    "backend_image_source": "",
                    "edge_resolved": "github-release:wasmerio/edge:v1:edge",
                    "local_test_command": "pnpm exec jest",
                    "compose_project_name": "wit_x",
                    "docker_cli_path": "/usr/bin/docker",
                    "docker_buildx_path": "/usr/libexec/docker/cli-plugins/docker-buildx",
                    "ports": {"backend_http": "18000", "mysql_app_db_1": "13306"},
                }
            ),
        )
        flat = read_resolved_json(path)
        self.assertEqual(flat["BACKEND_VERSION"], "resolve_prod")
        self.assertEqual(flat["BACKEND_HTTP_PORT"], "18000")
        self.assertEqual(flat["MYSQL_APP_DB_1_PORT"], "13306")
        self.assertEqual(flat["LOCAL_TEST_COMMAND"], "pnpm exec jest")


class TestPackageList(TempDirTest):
    def test_merge_dedupe_and_comments(self) -> None:
        seed = self.write(
            "seed.json",
            json.dumps(
                {
                    "resolved": [
                        {"resolvedName": "wasmer/pkg-a", "resolvedVersion": "1.0.0"},
                        {"resolvedName": "wasmer/pkg-a", "resolvedVersion": "1.0.0"},
                        {"resolvedName": None, "resolvedVersion": "2.0"},
                    ]
                }
            ),
        )
        extra = self.write(
            "extra.txt",
            "# a comment\n"
            "wasmer/pkg-b@=2.0.0  # pinned for tests\n"
            "\n"
            "wasmer/pkg-a@=1.0.0\n",
        )
        output = self.tmp / "resolved.txt"
        packages = _build_package_list(seed, extra, output)
        self.assertEqual(packages, ["wasmer/pkg-a@=1.0.0", "wasmer/pkg-b@=2.0.0"])
        self.assertEqual(
            output.read_text(), "wasmer/pkg-a@=1.0.0\nwasmer/pkg-b@=2.0.0\n"
        )

    def test_missing_inputs_give_empty_list(self) -> None:
        output = self.tmp / "resolved.txt"
        packages = _build_package_list(
            self.tmp / "nope.json", self.tmp / "nope.txt", output
        )
        self.assertEqual(packages, [])


class TestRedaction(unittest.TestCase):
    def test_tokens_redacted(self) -> None:
        raw = (
            "WASMER_TOKEN=wap_secret123\n"
            "export EDGE_SYNC_TOKEN=abc.def\n"
            "OTHER=untouched\n"
        )
        redacted = _REDACT_PATTERN.sub(r"\1<redacted>", raw)
        self.assertNotIn("wap_secret123", redacted)
        self.assertNotIn("abc.def", redacted)
        self.assertIn("WASMER_TOKEN=<redacted>", redacted)
        self.assertIn("OTHER=untouched", redacted)


class TestJwt(TempDirTest):
    @unittest.skipUnless(shutil.which("openssl"), "openssl not available")
    def test_structure_and_signature(self) -> None:
        import base64

        key = self.tmp / "key.pem"
        subprocess.run(
            ["openssl", "genrsa", "-out", str(key), "2048"],
            check=True,
            capture_output=True,
        )
        token = sign_edge_grpc_token(key)
        header_b64, payload_b64, signature_b64 = token.split(".")

        def decode(part: str) -> bytes:
            return base64.urlsafe_b64decode(part + "=" * (-len(part) % 4))

        self.assertEqual(json.loads(decode(header_b64)), {"alg": "RS512", "typ": "JWT"})
        payload = json.loads(decode(payload_b64))
        self.assertEqual(payload["sub"], "wasmerio-backend")
        self.assertEqual(payload["node_api_permissions"], ["all"])
        self.assertEqual(payload["exp"] - payload["iat"], 30 * 24 * 60 * 60)

        # Verify the RS512 signature with openssl against the public key.
        public = self.tmp / "pub.pem"
        subprocess.run(
            ["openssl", "rsa", "-in", str(key), "-pubout", "-out", str(public)],
            check=True,
            capture_output=True,
        )
        signature_file = self.tmp / "sig.bin"
        signature_file.write_bytes(decode(signature_b64))
        verify = subprocess.run(
            [
                "openssl",
                "dgst",
                "-sha512",
                "-verify",
                str(public),
                "-signature",
                str(signature_file),
            ],
            input=f"{header_b64}.{payload_b64}".encode(),
            capture_output=True,
        )
        self.assertEqual(verify.returncode, 0, verify.stderr)


class TestProdTagPattern(unittest.TestCase):
    def test_prod_tags_have_no_channel_suffix(self) -> None:
        from localplatform.resolve import _PROD_TAG_PATTERN

        for prod in ("v2026-07-06_0_ff0e329", "v2026-07-02_3_fdd0152"):
            self.assertIsNotNone(_PROD_TAG_PATTERN.fullmatch(prod), prod)
        for non_prod in (
            "v2026-07-07_3_2af698b_dev",
            "v2026-07-07_2_c8d095c_bugt",
            "v2026-07-07_5_4cfc7b4_dev1",
            "latest",
        ):
            self.assertIsNone(_PROD_TAG_PATTERN.fullmatch(non_prod), non_prod)


class TestDescribeArtifactSource(unittest.TestCase):
    def test_selector_shapes(self) -> None:
        self.assertEqual(
            describe_artifact_source(
                "github-release:wasmerio/edge:v2026-07-07_5_4cfc7b4_dev1:edge"
            ),
            "v2026-07-07_5_4cfc7b4_dev1 (github-release from wasmerio/edge)",
        )
        self.assertEqual(
            describe_artifact_source("github-artifact:wasmerio/backend:backend-image"),
            "backend-image (latest artifact from wasmerio/backend)",
        )
        self.assertEqual(
            describe_artifact_source("artifact:wasmerio/backend:12345:backend-image"),
            "backend-image (artifact from wasmerio/backend run 12345)",
        )
        self.assertEqual(
            describe_artifact_source("path:/opt/edge-binary"), "path:/opt/edge-binary"
        )
        self.assertEqual(
            describe_artifact_source("ghcr.io/wasmerio/backend:v1.2.3"),
            "ghcr.io/wasmerio/backend:v1.2.3",
        )

    def test_backend_description_includes_archive_source(self) -> None:
        ctx = Ctx(
            env={
                "BACKEND_IMAGE_REF": "local-platform-backend:wit_x",
                "BACKEND_IMAGE_SOURCE": "github-release:wasmerio/backend:v2:*image*.tar",
            }
        )
        self.assertEqual(
            describe_backend_version(ctx),
            "local-platform-backend:wit_x "
            "(from v2 (github-release from wasmerio/backend))",
        )
        ctx_pull = Ctx(
            env={"BACKEND_IMAGE_REF": "ghcr.io/x/y:1", "BACKEND_IMAGE_SOURCE": ""}
        )
        self.assertEqual(describe_backend_version(ctx_pull), "ghcr.io/x/y:1")


class TestFormatting(unittest.TestCase):
    def test_human_bytes(self) -> None:
        self.assertEqual(human_bytes(0), "0B")
        self.assertEqual(human_bytes(1023), "1023B")
        self.assertEqual(human_bytes(1024), "1.0KB")
        self.assertEqual(human_bytes(338130360), "322.5MB")

    def test_format_duration(self) -> None:
        self.assertEqual(format_duration(0), "0m00s")
        self.assertEqual(format_duration(120000), "2m00s")
        self.assertEqual(format_duration(61500), "1m01s")


if __name__ == "__main__":
    unittest.main()
