name: "Setup Test Environment"
description: "Sets up the environment for Wasmer integration tests"

inputs:
  fetch_artifact:
    description: "Set to the name of artifact you want to overwrite the default wasmer binary with"
    required: false

runs:
  using: "composite"
  steps:
    - uses: wasmerio/setup-wasmer@v2
    - name: Add pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Setup jest
      shell: bash
      run: make setup
    - uses: actions/download-artifact@v4
      if: inputs.fetch_artifact != ''
      with:
        name: ${{ inputs.fetch_artifact }}
    - name: Overwrite wasmer binary
      if: inputs.fetch_artifact
      shell: bash
      run: |
        tar -xzf build-wasmer.tar.gz
        cp ./bin/wasmer ~/.wasmer/bin/wasmer
