name: Code QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: code-qa
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/integration-test-workflow.yaml
    with:
      test_branch: ${{ github.head_ref }}
      provide_quality_assessment: true
    secrets:
      token: ${{ secrets.WAPM_DEV_TOKEN }}
      test_failure_webhook: ${{ secrets.SLACK_WH_INTEG_TEST_FAIL_DEV }}

  fmt:
    name: File format check
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Add pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup project
        shell: bash
        run: make setup

      - name: Check prettier
        run: |
          make fmt-check

  lint:
    name: Lint the project
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Add pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup project
        shell: bash
        run: make setup

      - name: Check tsc and eslint
        run: |
          make check
