name: Code QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: wasmerio/wasmer-integration-tests/.github/workflows/integration-test-workflow.yaml@sre-183-integration-tests-exec-cronjob-cli-log-validation
    secrets:
      WAPM_DEV_TOKEN: ${{ secrets.WAPM_DEV_TOKEN }}

  fmt:
    name: File format check
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format & fail on changes
        run: |
          deno fmt --check

  lint:
    name: Lint the project
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno lint
        run: |
          deno lint
