name: Code QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: code-qa
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/integration-test-workflow.yaml
    secrets:
      token: ${{ secrets.WAPM_DEV_TOKEN }}

  fmt:
    name: File format check
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format & fail on changes
        run: |
          make fmt-check

  lint:
    name: Lint the project
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno lint
        run: |
          make check
