name: Code QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Allow one concurrent deployment per branch
concurrency:
  group: ${{ github.ref }}-code-qa
  cancel-in-progress: true

jobs:
  tests:
    uses: wasmerio/wasmer-integration-tests/.github/workflows/integration-test-workflow.yaml@fix-issues-in-integration-test-workflow
    secrets:
      wasmer_token: ${{ secrets.WAPM_DEV_TOKEN }}

  fmt:
    name: File format check
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format & fail on changes
        run: |
          deno fmt --check

  gh-lint:
    name: Lint GH actions
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: actionlint
        id: actionlint
        uses: raven-actions/actionlint@v2
        with:
          cache: false # optional

      - name: actionlint Summary
        if: failure()
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
  lint:
    name: Lint the project
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno lint
        run: |
          deno lint
