name: Integration tests

'on':
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}-integration-tests
  cancel-in-progress: true


jobs:
  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: unlock git-crypt
        run: |
          sudo apt-get install git-crypt -y
          echo "${{ secrets.GIT_CRYPT_KEY_BASE64 }}" | base64 -d > crypt.key
          git crypt unlock crypt.key
      - id: 'auth'
        name: Install google cloud auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '410.0.0'
          project_id: wasmer
      - name: Configure docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: run servers
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup poetry
        run: |
          pip install poetry
          poetry --version
      - name: Run pytests
        run: |
          poetry run -- pytest tests
