name: Purge old test apps

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"

jobs:
  purge-old-test-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install deno
        uses: denoland/setup-deno@v1
      - name: Purge old test apps
        run: |
          ./bin/purge-old-apps.ts
