name: "Run tests with new tests pushed on main branch"
'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
      - 'fix-php-extensions-tests'

concurrency:
  group: push-to-main

jobs:
  default:
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: ${{ vars.MYSQL_HOST }}
      MYSQL_DBNAME: ${{ vars.MYSQL_DBNAME }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_PORT: ${{ vars.MYSQL_PORT }}
      MYSQL_CERT: ${{ secrets.MYSQL_CERT }}
      PG_HOST: ${{ vars.PG_HOST }}
      PG_DBNAME: ${{ vars.PG_DBNAME }}
      PG_USERNAME: ${{ secrets.PG_USERNAME }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_PORT: ${{ vars.PG_PORT }}
    steps:
      - uses: actions/checkout@v3
      - uses: wasmerio/setup-wasmer@v2
      - run: |
          # login to wasmer registry
          wasmer config set registry.url https://registry.wasmer.wtf/graphql
          wasmer login ${{ secrets.WAPM_DEV_TOKEN }}
          wasmer whoami

          cargo test test_php_extensions --no-fail-fast -- --test-threads 1