name: "Run tests with new tests pushed on main branch. Intended to be run via workflow dispatch to validate dev environment."
"on":
  workflow_dispatch:

concurrency:
  group: push-to-main

jobs:
  tests:
    uses: ./.github/workflows/test-jobs.yaml
    secrets:
      WAPM_DEV_TOKEN: ${{ secrets.WAPM_DEV_TOKEN }}
    steps:
      - name: notify failure in slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Integration tests failed ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          https://hooks.slack.com/services/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
