name: "Run tests with new tests pushed on main branch"
'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: push-to-main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasmerio/setup-wasmer@v2
      - name: Cargo Registry Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/advisory-db
            ~/.cargo/git
            ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo target cache
        uses: actions/cache@v3
        with:
          path: |
            target/
          key: cargo-release-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          docker build -t tmp .
          docker run -v $PWD:/app -w /app tmp bash -c " \
            export MYSQL_HOST='${{ vars.MYSQL_HOST }}' &&\
            export MYSQL_DBNAME='${{ vars.MYSQL_DBNAME }}' &&\
            export MYSQL_USERNAME='${{ secrets.MYSQL_USERNAME }}' &&\
            export MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}' &&\
            export MYSQL_PORT='${{ vars.MYSQL_PORT }}' &&\
            export MYSQL_CERT='${{ secrets.MYSQL_CERT }}' &&\
            export PG_HOST='${{ vars.PG_HOST }}' &&\
            export PG_DBNAME='${{ vars.PG_DBNAME }}' &&\
            export PG_USERNAME='${{ secrets.PG_USERNAME }}' &&\
            export PG_PASSWORD='${{ secrets.PG_PASSWORD }}' &&\
            export PG_PORT='${{ vars.PG_PORT }}' &&\
            wasmer config set registry.url https://registry.wasmer.io/graphql &&\
            wasmer login ${{ secrets.WAPM_PROD_TOKEN }} &&\
            wasmer config set registry.url https://registry.wasmer.wtf/graphql &&\
            wasmer login ${{ secrets.WAPM_DEV_TOKEN }} &&\
            cargo test --no-fail-fast"
      - name: notify failure in slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Integration tests failed ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' https://hooks.slack.com/services/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
